export const FETCH_LOCALIZATION = 'FETCH_LOCALIZATION';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const FETCH_ORBIT_DATA = 'FETCH_ORBIT_DATA';
export const UPLOAD_LIST = 'UPLOAD_LIST';
export const UPLOAD_ITEM_PENDING = 'UPLOAD_ITEM_PENDING';
export const UPLOAD_ITEM_SUCCEEDED = 'UPLOAD_ITEM_SUCCEEDED';
export const UPLOAD_ITEM_FAILED = 'UPLOAD_ITEM_FAILED';
