export const FETCH_LOCALIZATION = 'FETCH_LOCALIZATION';
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const FETCH_ORBIT_DATA = 'FETCH_ORBIT_DATA';
export const FETCH_AUTH_USER = 'FETCH_AUTH_USER';