export enum ArtifactTypeSlug {
  Vernacular = 'vernacular',
  WholeBackTranslation = 'wholebacktranslation',
  PhraseBackTranslation = 'backtranslation',
  Retell = 'retell',
  QandA = 'qanda',
  Comment = 'comment',
  Activity = 'activity',
  Resource = 'resource',
  SharedResource = 'sharedresource',
  ProjectResource = 'projectresource',
  IntellectualProperty = 'intellectualproperty',
  KeyTerm = 'keyterm',
  Title = 'title',
  Graphic = 'graphic',
  AIResource = 'airesource',
}
