export const LOGIN_USER = 'LOGIN_USER';
export const FETCH_SCHEME_PENDING = 'FETCH_SCHEME_PENDING';
export const FETCH_SCHEME_FULFILLED = 'FETCH_SCHEME_FULFILLED';
export const FETCH_TASK_PENDING = 'FETCH_TASK_PENDING';
export const FETCH_TASK_FULFILLED = 'FETCH_TASK_FULFILLED';